package com.netflix.eventbus.impl;

/**
 * An interface for all event batches generated by eventbus for various batching strategies.
 *
 * @author Nitesh Kant
 */
public interface EventBatch extends Iterable {
}
